/** Styles for ConversationDetailScreen — split out to keep the screen under the size ceiling. */

import { StyleSheet } from 'react-native';
import { fontFamily, space, target, type as ty, hairline, radius, boundedContent, type Colors } from '../theme';

export function makeStyles(c: Colors) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: c.bg },
    flex: { flex: 1 },
    pressed: { opacity: 0.6 },
    // Generous bottom padding so the last field scrolls clear of the keyboard
    // and content never hides behind the floating Save button.
    content: { ...boundedContent, paddingHorizontal: space.s5, paddingBottom: 160 },
    sectionLabel: {
      ...ty.xs,
      fontFamily: fontFamily.sansSemibold,
      color: c.fgMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      paddingTop: space.s6,
      paddingBottom: space.s3,
    },
    chips: { flexDirection: 'row', flexWrap: 'wrap', gap: space.s2 },
    chip: {
      paddingHorizontal: space.s4,
      paddingVertical: space.s2,
      borderRadius: radius.pill,
      backgroundColor: c.bgSubtle,
      borderWidth: hairline,
      borderColor: c.hairline,
    },
    chipOn: { backgroundColor: c.fg, borderColor: c.fg },
    chipText: { ...ty.sm, fontFamily: fontFamily.sans, color: c.fg },
    chipTextOn: { color: c.bg, fontFamily: fontFamily.sansSemibold },
    input: {
      minHeight: target.min,
      paddingHorizontal: space.s4,
      borderRadius: radius.md,
      backgroundColor: c.bgSubtle,
      ...ty.base,
      fontFamily: fontFamily.sans,
      color: c.fg,
    },
    notes: {
      ...ty.base,
      fontFamily: fontFamily.sans,
      color: c.fg,
      minHeight: 88,
      borderRadius: radius.md,
      backgroundColor: c.bgSubtle,
      padding: space.s4,
    },
    note: {
      marginTop: space.s4,
      padding: space.s4,
      borderRadius: radius.md,
      backgroundColor: c.bgSubtle,
      borderLeftWidth: 3,
      borderLeftColor: c.appAccent,
    },
    noteText: { ...ty.sm, fontFamily: fontFamily.sans, color: c.fg },
    hadBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: space.s2,
      minHeight: target.min,
      borderRadius: radius.md,
      borderWidth: 1.5,
      borderColor: c.accent,
      paddingHorizontal: space.s5,
      marginTop: space.s8,
    },
    hadBtnText: { ...ty.base, fontFamily: fontFamily.sansSemibold, color: c.fg },
    hadBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: space.s2,
      marginTop: space.s8,
      paddingVertical: space.s2,
    },
    hadBannerText: { ...ty.base, fontFamily: fontFamily.sansSemibold, color: c.fg },
    reopenRow: { flexDirection: 'row', alignItems: 'center', gap: space.s2, marginTop: space.s4, paddingVertical: space.s2 },
    reopenText: { ...ty.sm, fontFamily: fontFamily.sans, color: c.fgMuted },
    deleteRow: { flexDirection: 'row', alignItems: 'center', gap: space.s2, marginTop: space.s8, paddingVertical: space.s3 },
    deleteText: { ...ty.base, fontFamily: fontFamily.sans, color: c.fgMuted },
    linkRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: space.s2,
      marginTop: space.s3,
      paddingVertical: space.s2,
    },
    linkText: { ...ty.sm, fontFamily: fontFamily.sans, color: c.fgMuted },
    linkedText: { flex: 1, ...ty.sm, fontFamily: fontFamily.sansSemibold, color: c.fg },
    changeText: { ...ty.sm, fontFamily: fontFamily.sansSemibold, color: c.appAccent },
    saveFab: {
      position: 'absolute',
      right: space.s6,
      bottom: space.s7,
      flexDirection: 'row',
      alignItems: 'center',
      gap: space.s2,
      height: 52,
      paddingHorizontal: space.s6,
      borderRadius: radius.pill,
      backgroundColor: c.inkButton,
      justifyContent: 'center',
    },
    saveFabPressed: { opacity: 0.85 },
    saveFabText: { ...ty.base, fontFamily: fontFamily.sansSemibold, color: c.inkButtonText },
  });
}
