/**
 * The canonical "More from Josh Approved" catalog — the single source of the
 * studio's live mobile apps, used by the quiet in-app cross-promo row
 * (MoreFromJA.tsx). Synced from the factory by `sync.mjs more-from-ja` (and
 * carried by the app shell); edit HERE, never per app, so every app's
 * cross-promo updates from one place on its next release.
 *
 * Canon (`canonical-voice.md` § Truth standard): the cross-promo row is the ONE
 * allowed exception to "No ads, ever" — and only because it is plain text, not
 * an ad unit. No tracking of taps, no network calls, no images.
 *
 * WHERE A ROW SENDS THE USER (Josh, 2026-08-21). Every row opens the app's page
 * on joshapproved.com with `?install=1`, never a store listing directly. That
 * page sends a phone straight on to the right store for its platform, and gives
 * anyone else the studio site to look around. A direct store link spends the tap
 * and teaches the reader nothing about the rest of the catalogue, which is the
 * whole point of the row.
 *
 * WHY THE LIVE FLAGS ARE GENERATED. A row only ever appears when the target app
 * is genuinely live on the user's platform, so it can never point at a page
 * whose store button does not exist yet. That fact used to be a hand-maintained
 * URL per app with a comment saying "add a URL here the moment an app goes
 * live", and predictably nobody ever did: for months the row showed exactly one
 * app (Workout Timer) while four others were live on both stores. The flags are
 * now written by `josh-approved-factory/scripts/sync-ja-catalog.mjs` from real
 * store status, and checked daily by the `site-parity` job. Do not hand-edit the
 * `iosLive` / `androidLive` lines; edit the name and blurb, which are voice.
 *
 * `slug` MUST match the app's public repo slug (the last path segment of
 * REPO_URL) — that's how an app excludes itself from its own row. `webSlug` is
 * the app's page on the site, which differs for one app (workout-timer ships as
 * free-workout-timer on the web).
 */

export type JaCatalogEntry = {
  slug: string;
  /** The app's page slug on joshapproved.com. Defaults to `slug`. */
  webSlug?: string;
  name: string;
  /** One plain line — what it does. Sentence case, voice canon. No claims. */
  blurb: string;
  /** GENERATED — live on the App Store. See sync-ja-catalog.mjs. */
  iosLive: boolean;
  /** GENERATED — live on Google Play. See sync-ja-catalog.mjs. */
  androidLive: boolean;
};

/** The site page that fronts both stores for an app.
 *  Note the trailing slash before the query: without it the site answers with a
 *  308 to the slashed form, costing every tap an extra round trip on mobile. */
export function installUrl(entry: JaCatalogEntry): string {
  return `https://joshapproved.com/apps/${entry.webSlug ?? entry.slug}/?install=1`;
}

// LIVE-FLAGS:START (generated by josh-approved-factory/scripts/sync-ja-catalog.mjs — do not hand-edit the iosLive/androidLive lines)
export const JA_CATALOG: JaCatalogEntry[] = [
  {
    slug: 'workout-timer',
    webSlug: 'free-workout-timer',
    name: 'Workout Timer',
    blurb: 'Interval timer for Tabata and HIIT.',
    iosLive: true,
    androidLive: true,
  },
  {
    slug: 'grocery-list',
    name: 'Grocery List',
    blurb: 'A shared shopping list that stays in sync.',
    iosLive: true,
    androidLive: true,
  },
  {
    slug: 'split-expenses',
    name: 'Split Expenses',
    blurb: 'Split shared costs and see who owes whom.',
    iosLive: false,
    androidLive: false,
  },
  {
    slug: 'packing-list',
    name: 'Packing List',
    blurb: 'A checklist that builds itself from your trip.',
    iosLive: true,
    androidLive: true,
  },
  {
    slug: 'tend',
    name: 'Relationships',
    blurb: 'A quiet place to keep up with the people you care about.',
    iosLive: false,
    androidLive: true,
  },
  {
    slug: 'home-maintenance',
    name: 'Home Upkeep',
    blurb: 'Home maintenance reminders, plus your appliances and where to find their manuals.',
    iosLive: true,
    androidLive: true,
  },
  {
    slug: 'tally',
    name: 'Tally',
    blurb: 'A simple counter for anything you count.',
    iosLive: false,
    androidLive: false,
  },
  {
    slug: 'budget',
    name: 'Budget',
    blurb: 'See where the money goes, privately.',
    iosLive: false,
    androidLive: false,
  },
];
// LIVE-FLAGS:END

/** The live entries for the current platform, excluding the host app. Pure —
 *  no React, no RN imports — so it's testable and reusable. */
export function moreFromJA(
  os: 'ios' | 'android' | string,
  excludeSlug?: string
): Array<JaCatalogEntry & { url: string }> {
  return JA_CATALOG.filter((a) => a.slug !== excludeSlug)
    .filter((a) => (os === 'android' ? a.androidLive : a.iosLive))
    .map((a) => ({ ...a, url: installUrl(a) }));
}
